### ISSUE TITLE
Removal of the renderer option for maps

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#113]
According to [release notes](https://github.com/openlayers/openlayers/releases/tag/v5.0.0), the `renderer` option has been removed from the `Map` constructor in ol v5.0.0
So `renderer` option in `vl-map` component ([link](https://github.com/ghettovoice/vuelayers/blob/a625a1f85380efaa2b1f785cd0ea8415c19990b9/src/component/map/map.vue#L98-L101)) doesn't make sense now. Or `WebGLMap` should be used if 'webgl' was passed as `renderer` property. But most likely it must be another component

**Comment by ghettovoice** [comment]
Thank @become-iron for the note.  

I need to check if different map implementation in the openlayers now have significantly different public interface. If no may be it can be hidden in the vuelayers like it was before.  
Or may be introduce new map components for each openlayers map (`vl-map-canvas`, `vl-map-webgl`) but 
hold `vl-map` for backward compatibility

**Comment by ghettovoice** [comment]
Obviously this comment is outdated a bit.
I added it a long time ago, now it should be changed by the work on this issue.

**Comment by become-iron** [comment]
I think it shouldn't be closed yet

**Comment by become-iron** [comment]
@ghettovoice I think this one should be pinned as well

**Comment by ghettovoice** [comment]
Yep

**Comment by ghettovoice** [comment]
Done as `renderer` prop with watcher. 
Possible values: 'canvas' (default), 'webgl'

**Comment by krizman** [comment]
I have noticed [`renderer` property](https://github.com/ghettovoice/vuelayers/blob/v0.11.28/src/component/map/map.vue#L133) was still present in v0.11.28 but has disappeared in latest v0.12.
This is probably because [OL does not support it anymore](https://github.com/openlayers/openlayers/blob/b759c7e08dc382747b79dcd7cd21722bd2a8d99c/changelog/upgrade-notes.md#drop-of-support-for-the-experimental-webgl-renderer).

Just wanted to point out that the current docs still have [`renderer` property on map.vue](https://github.com/ghettovoice/vuelayers/blob/master/docs/component/map.md#renderer).

**Comment by ghettovoice** [comment]
@krizman yep, I know. Current published documentation is still for v0.11.
Thanks for report!
