### ISSUE TITLE
vuelayers  recursive loop bug

### ISSUE THREAD

**Issue by Razz21** [ghettovoice/vuelayers#238]
`Ol: v5.3.3`
`Vuelayers: v0.11.7`
Hi, i've just upgraded vuelayers and got this error in console:
`[Vue warn]: Error in nextTick: "InternalError: too much recursion"`

template:
```
<vl-layer-vector>
    <vl-source-cluster :distance="50">
        <vl-source-vector ref="featuresSource" @mounted="getFeatures"></vl-source-vector>
    </vl-source-cluster>
    <vl-style-func :factory="makeClusterStyleFunc"></vl-style-func>
</vl-layer-vector>
````
i realized that error is caused by this method:
```
getFeatures() {
   const sourceVm = this.$refs.featuresSource;
   sourceVm.$source.clear();
   const features = this.places.map(i => {
       const geometry = new Point(i.geo);
       geometry.transform("EPSG:4326", "EPSG:3857");
       let feature = new Feature({geometry});
      feature.setProperties(i);
      feature.setId(i.id);
      return feature;
   });
   sourceVm.$source.addFeatures(features);
},
```
In `v0.11.5-beta.8` there is no error. Is it bug, or my method/template is incorrect?

**Comment by ghettovoice** [comment]
Hello @Razz21!
Looks like a bug, I'll try to resolve it soon.
Thanks for response!

**Comment by Razz21** [comment]
i found this bug is caused by this line
`sourceVm.$source.addFeatures(features)`

**Comment by ghettovoice** [comment]
@Razz21 do you experience this issue when using UMD version of the VueLayers?
I can reproduce it with UMD version, and no errors with ES version.
Looks like it was mistake include some part of OpenLayers stuff into UMD build

**Comment by ghettovoice** [comment]
Yeh, there was conflicts between types.
Now it should be resolved with v0.11.8. Upgrade please
https://jsfiddle.net/ghettovoice/gf3aje4r/

**Comment by Razz21** [comment]
In clean environment works fine now, but error still exists in my project, probably there is some problem with my configuration. Thank you.

**Comment by ghettovoice** [comment]
Same error? Or something else?

**Comment by Razz21** [comment]
I think i resolved this issue. I deleted package-lock.json before reinstalling node modules, error is gone now, hope for good. Thank you again.

**Comment by ghettovoice** [comment]
Great!
